### ISSUE TITLE
Unrequire parameters

### ISSUE THREAD

**Issue by rowrowrowrow** [anttiviljami/openapi-client-axios#100]
Currently if you don't specify parameters for an operation several errors occur in getRequestConfigForOperation. It doesn't make sense to require parameters to be set if the path doesn't have any parameters and if we already `default all params to query if operation doesn't specify param`.

We should provide a default value of an empty array for 'parameters' getRequestConfigForOperation.

We could also ensure that op.parameters is set to an empty array in getOperations, but we may need to know that no parameters we're specified in the spec in other places.

**Comment by styks1987** [comment]
I have this exact same issue.

**Comment by rowrowrowrow** [comment]
> I have this exact same issue.

PR Here: https://github.com/anttiviljami/openapi-client-axios/pull/101

**Comment by anttiviljami** [comment]
Fixed and released as part of `openapi-client-axios@4.6.0` release
