### ISSUE TITLE
openapi-types shouldn't be a runtime dependency

### ISSUE THREAD

**Issue by nponeccop** [anttiviljami/openapi-client-axios#102]
It isn't used at runtime.

**Comment by anttiviljami** [comment]
it's not a runtime dependency but it is a dependency for the types provided by this package, thus can't be a devDependency.

**Comment by nponeccop** [comment]
I wonder what a common solution is. Now this package is deployed in production, which is wrong, too.

**Comment by anttiviljami** [comment]
What do you mean by deployed in production? Perhaps you should use a bundler. :)
