### ISSUE TITLE
openapi-client-axios-typegen 5.0.0 depends on an older openapi-client-axios

### ISSUE THREAD

**Issue by nponeccop** [anttiviljami/openapi-client-axios#108]
https://github.com/anttiviljami/openapi-client-axios/blob/d44e392a20b083be7ae20231eda1292f10e9e32a/packages/typegen/package.json

This dependency should be changed to ^5.0.0 as early versions won't work with axios 0.25.

**Comment by anttiviljami** [comment]
Thanks! Fixed in `openapi-client-axios-typegen@5.0.1`
