### ISSUE TITLE
Improve Lodash imports for tree-shaking

### ISSUE THREAD

**Issue by markerikson** [anttiviljami/openapi-client-axios#11]
Hi.  I was glancing through this lib to evaluate whether it might be a good fit for our app, and I noticed that it currently imports Lodash as a default import:

`import _ from "lodash"`

This will likely cause the entire Lodash library to be pulled in and increase bundle sizes for apps.  It would probably be better if the individual functions were imported seperately, like `import flatMap from "lodash/flatMap"`.

**Comment by ptytb** [comment]
It seems that still wouldn't be enough because of the dependency [json-schema-deref-sync](https://github.com/cvent/json-schema-deref-sync) uses the whole bloated lodash as well.

`yarn why lodash`

```
- Hoisted from "openapi-client-axios#lodash"
- Hoisted from "openapi-client-axios#json-schema-deref-sync#lodash"

```

Shouldn't be hard to switch both to use `lodash-es` though.

**Comment by anttiviljami** [comment]
Although it would be super cool to get the bundle size down, like @ptytb mentioned, right now getting rid of lodash as a default export wouldn't have an effect.

I'll be closing this issue but if you have any ideas, I'd be more than happy to receive PRs :)
