### ISSUE TITLE
How to infer operation method names from endpoint details?

### ISSUE THREAD

**Issue by ixxie** [anttiviljami/openapi-client-axios#120]
Forgive me if this is a naive question (I am new to OpenAPI as well as this library) but - how do I infer what my operation method name should be based on the endpoint's path and type? Is this documented somewhere?

(Also - sorry for posting this question as an issue but I didn't know where else to ask)

**Comment by anttiviljami** [comment]
Operation method names are not inferred. They are set by the operationId property
