### ISSUE TITLE
Issue persist when trying to run with react native

### ISSUE THREAD

**Issue by FranDepascuali** [anttiviljami/openapi-client-axios#146]
Thank you @anttiviljami for fixing the previous issue #140 I reported! 

When I try, I still have errors regarding dependencies not supported in our node.js runtime due to `json-schema-ref-parser`. 

<img width="752" alt="imagen" src="https://user-images.githubusercontent.com/12101394/213734347-e04b94cb-343b-4369-a365-b89ef7f6118d.png">

Thank you!
Depa

**Comment by anttiviljami** [comment]
Hi @FranDepascuali, you’ll still need to add a polyfills in your build config. Take a look at the README for examples: 

https://github.com/anttiviljami/openapi-client-axios#browser-usage

**Comment by FranDepascuali** [comment]
It's really difficult to add a polyfill in react-native like that as it doesn't use a webpack setup. 

Been reading into https://github.com/philikon/ReactNativify and https://github.com/tradle/rn-nodeify
but it sounds pretty complicated.

I will tell you if I had any luck.

Thanks!

**Comment by anttiviljami** [comment]
This seems like a straightforward solution for rn. https://stackoverflow.com/a/41511414

There might be other polyfills you need too like `util` IIRC

**Comment by FranDepascuali** [comment]
Try that lib
<img width="359" alt="image" src="https://user-images.githubusercontent.com/12101394/213933887-ee5ae6b9-a880-4404-9231-b92c07e159b2.png">

**Comment by FranDepascuali** [comment]
Update: I tried every possible way I could, using different polyfill implementation.

I couldn't make it work, there's always strange runtime errors when polyfilling.

I tried other alternatives to generate a typescript axios client (gonna list them later).
The work BUT this lib has two important aspects:
1. Is used by our company frontend's, meaning that we have easier code reuse
2. I really like the types paths objects. That would also allow to do type safe axios mocking via interceptors. Plus it provides better communication with the backend team.
I couldn't find that typed paths property dictionary in other packages.

This lib seems awesome. I'll try other versions to see if the errors change or it's available for us with react native.

Thanks you very much @anttiviljami !!

Depa

**Comment by anttiviljami** [comment]
Hi @FranDepascuali. The issues come from the `json-schema-ref-parser` dependency used by this library. 

Unfortunately this lib is no longer really maintained and causes multiple issues for us, including a bloated bundle size and difficulty in non Node.js environments.

I’ve asked my team at @epilot-dev to take a look at replacing with a simpler, more compatible implementation. A lot of the features from `json-schema-ref-parser` are not really necessary for openapi-client-axios
