### ISSUE TITLE
How does it work? 

### ISSUE THREAD

**Issue by kayode-adechinan** [anttiviljami/openapi-client-axios#149]
First, thanks for the library.

I am using the following snippet with typescript: 

```typescript
import OpenAPIClientAxios from "openapi-client-axios";


export const demo = async () => {

  const api = new OpenAPIClientAxios({
    definition: "http://localhost:8080/openapi-specs.json",
    });
  
  api.init();

  const client = await api.getClient();

  await client....
};


```

And i am not getting any autocompletion...

Am i missing something ?

**Comment by anttiviljami** [comment]
See https://github.com/anttiviljami/openapi-client-axios/blob/master/packages/openapi-client-axios/README.md#generating-type-files-dts
