### ISSUE TITLE
Why it fetch the definition every time, Can it do that in typegen process ?

### ISSUE THREAD

**Issue by panudetjt** [anttiviljami/openapi-client-axios#151]
Hello,
  Thank you for created great library. 
  I'm very new to openAPI. I wonder why the client have to fetch the definition every time before I want to use the api even I generate type with typegen.
  Or this is the industrial-standard ?

Thank you.

**Comment by anttiviljami** [comment]
You can avoid the fetch by directly passing the definition as an object instead of URL.
