### ISSUE TITLE
Support for axios 0.27.x

### ISSUE THREAD

**Issue by dvrylc** [anttiviljami/openapi-client-axios#159]
I'm working on a codebase that is pinned on axios `0.27.2`. 

The current peer dependency specified is `^0.25.0` -- this only covers `0.25.0` ([check here](https://semver.npmjs.com/)) and not `0.26.x` or `0.27.x` because [only patch updates are allowed for `^0.x` caret ranges](https://github.com/npm/node-semver#caret-ranges-123-025-004). 

Can we extend support to `0.27.x`? Thinking a range like `>=0.25 <=0.27` should work. 

Thanks!

**Comment by anttiviljami** [comment]
Hi @dvrylc! Thanks for the detailed bug report.

Support for `axios@>0.25` was added in `openapi-client-axios@7.3.0`

https://github.com/anttiviljami/openapi-client-axios/commit/549bf9b8a9d5dbb692db45f6e521ea2912843e8f#diff-02b96681c77e402830334332f95b59e318db55981ef8cbf00bea768fac0a0bc2R42
