### ISSUE TITLE
Enum map support

### ISSUE THREAD

**Issue by nrl240** [anttiviljami/openapi-client-axios#161]
Hello!

Any plans to incorporate support for generating an enum such as the following?
```ts
export enum DailySetting {
    '1:4' = 'Quarter of a day',
    '1:2' = 'Half of a day',
    '3:4' = 'Three quarters of a day',
    '1:1' = 'Full day',
}
```

I saw [openapi-typescript-codegen](https://github.com/ferdikoomen/openapi-typescript-codegen) generate [enums with custom names and descriptions](https://github.com/ferdikoomen/openapi-typescript-codegen/blob/master/docs/custom-enums.md), which looks like good inspiration for this package.

**Comment by anttiviljami** [comment]
I personally prefer union types over enums, and we use a different library to generate the types so switching to enums is probably not something I'd vouch for right now 🙏
