### ISSUE TITLE
EventEmitter for openapi-client-axios

### ISSUE THREAD

**Issue by dannyhaak** [anttiviljami/openapi-client-axios#163]
We have a use case where we want to get events on when openapi-axios-client functions are called. The use case is that we have a platform with 'custom' JavaScript applications build by our users. Our users call openapi-axios-client functions to call our backend APIs. We want to add offline capabilities, however, we want to keep using openapi-axios-client as the 'main' frontend to our users (instead of a custom wrapper). One way of doing that would be to add events to openapi-axios-client to learn when functions are called, and when the results is obtained.

I am willing to make a PR to add this functionality - but before doing that - is this something you will merge into the main project?

**Comment by anttiviljami** [comment]
Hi @dannyhaak! Interesting use case.

Did you consider just using [axios interceptors](https://github.com/axios/axios#interceptors)? Do you see any reason this would't work in your case?

**Comment by dannyhaak** [comment]
Ah, that's an interesting option! Wasn't aware of that. Let me try that, and report back.

**Comment by dannyhaak** [comment]
Yes, it seems to work perfectly fine for my use case. Case closed :).
