### ISSUE TITLE
Issue with multipart/form-data requests

### ISSUE THREAD

**Issue by mathoglu** [anttiviljami/openapi-client-axios#17]
Working with a image upload endpoint and noticed the generated client do not work as expected for multipart/form-data requests. 

After some debugging it seems like the client creates a new FormData object and appends the files in the wrong way.

From the generated code:
```javascript
localVarFormParams.append('files', files.join(COLLECTION_FORMATS.csv));
```
This will produce a request containing "[Object File], [Object File]..." in the body. 

The correct way should be (tried it out and worked as expected) to something like
```javascript
files.forEach((f: File) => {
  localVarFormParams.append('files[]', f));
})
```
This will produce the correct request body as also demonstrated [here](https://developer.mozilla.org/en-US/docs/Web/API/FormData/append).

Im using the following OpenAPI definition for the endpoint:
```json
"/upload": {
      "post": {
        "tags": [
          "Upload"
        ],
        "requestBody": {
          "description": "File upload",
          "required": true,
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "files": {
                    "type": "array",
                    "items": {
                      "type": "string",
                      "format": "binary"
                    }
                  }
                }
              }
            }
          }
        },
        "responses": {...}
      }
    }
  }
```

**Comment by anttiviljami** [comment]
I don't believe openapi-client-axios has any special handling for `multipart/form-data`. Your problem must lie elsewhere. I'm not at all sure what you're talking about when you say "generated code". 

You should just use the underlying axios client to provide the corrext request body.
