### ISSUE TITLE
Global headers

### ISSUE THREAD

**Issue by timeconsumer** [anttiviljami/openapi-client-axios#18]
Is there a way to initialize a client with global headers so that you don't have to pass the same one for each request?

**Comment by anttiviljami** [comment]
Sure! https://github.com/anttiviljami/openapi-client-axios/blob/master/DOCS.md#parameter-optsaxiosconfigdefaults

**Comment by anttiviljami** [comment]
Also, the client instance is just an axios instance, so you can directly modify client.defaults.headers

**Comment by timeconsumer** [comment]
Thanks!

**Comment by paz** [comment]
This is no longer present in the documentation.
For those looking for it, see from the previous commit: https://github.com/openapistack/openapi-client-axios/blob/235fc7a578f11257c36c09ff27b0e90af68c5291/DOCS.md#authentication
