### ISSUE TITLE
Data Validation?

### ISSUE THREAD

**Issue by ramast** [anttiviljami/openapi-client-axios#27]
This is more of a question/feature request than an "issue".

Does the library perform validation on the input before sending it to the server?

For example given field like that

```json
"username": {
    "type": "string",
    "description": "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
    "pattern": "^[\\w.@+-]+\\Z",
    "maxLength": 150
}                  },
```
Would the library reject an input the exceed 150 character or doesn't match the pattern?

**Comment by anttiviljami** [comment]
No, `openapi-client-axios` doesn't perform any request validation based on the request schema. 

Check out[`openapi-backend/OpenAPIValidator`](https://github.com/anttiviljami/openapi-backend/blob/master/DOCS.md#class-openapivalidator) instead if you wish to do something like this. You could create an Axios requestInterceptor to do that.
