### ISSUE TITLE
Support user-configurable operation names

### ISSUE THREAD

**Issue by mdwheele** [anttiviljami/openapi-client-axios#30]
Hello!

Currently, the library relies _solely_ on `operationId` to determine the function name that is attached to clients when they are created. This is _certainly_ spec-compliant and will work for a majority of use-cases. 

Unfortunately, I'm currently in the minority! 😁 

I have an Express API I'm working on and I currently use a package which uses a few extended attributes to be able to perform automating wiring of the Express router as well as request/response validation. In this setup, my `operationId` are not unique. I have an open PR on this library to get us to the point where I may use `operationId` that look more like `resource.verb` (e.g. `pets.list`, `pets.create`, etc.) and not rely on the extended attributes.

Here, what if there were a new configuration option where an end-user could specify a pluggable strategy for determination of method names. This function, internally, would receive the current operation and would return a method name. This would allow me to map `pets.create` -> `createPet` (or whatever). 

The library would ship a default configuration that matches the current `operationId`-based implementation.

I am _more than happy_ to put together an initial implementation of this if you'd like to touch/feel it before further consideration. Just let me know!

**Implementation details**

We're basically looking to make https://github.com/anttiviljami/openapi-client-axios/blob/master/src/client.ts#L207 pluggable. So, at this point, the idea would be to call out to our "method name factory function" to determine the property that is assigned to the instance:

```js
for (const operation of operations) {
  const { operationId } = operation;
  if (operationId) {
    instance[this.getMethodName(operation)] = this.createOperationMethod(operation);
  }
}
```

`getMethodName` would be responsible for considering the configured factory and resolving the method name. Configuration of the factory might look like:

```
// operationNameFactory probably has a better name
new OpenAPIClientAxios({ 
  definition: 'https://example.com/api/openapi.json',
  operationNameFactory: (operation) {
    // Representing the current implementation. Simply 
    // use the operationId as the method name.
    return operation.operationId
  }
});
```

**Comment by anttiviljami** [comment]
I'm 100% on board with this idea. 

Please execute. <3

**Comment by anttiviljami** [comment]
@mdwheele still up to it? perhaps someone else can take this up? :)

**Comment by mdwheele** [comment]
Totally!

I've actually got some time tonight I can spend on it. Got pulled to another project at work that (unfortunately) doesn't have a spec yet so the immediate need went away, haha. 

Thanks for the reminder.

**Comment by mdwheele** [comment]
Hey @anttiviljami! 

I've put #41 up for review. Please let me know if there's additional work to be done and I'd be glad to help. Really looking forward to using this as it's going to save SO MUCH time on my end not having to write clients ❤️

**Comment by npdev453** [comment]
@anttiviljami, looks like resolved and work pretty awesome, maybe you can close that issue?
