### ISSUE TITLE
Upgrading to axios version 0.20.0 breaks generated `Bearer` Authorization token method client

### ISSUE THREAD

**Issue by infomofo** [anttiviljami/openapi-client-axios#37]
I upgraded from

```
-    "axios": "^0.19.2",
+    "axios": "^0.20.0",
```

And after that, my openapi calls that use the `Bearer` `Authorization` header token are consistently returning 403. Inspecting the network traffic it seems that after the axios upgrade, my generated axios client no longer is sending the required `Authorization` header at all. Is anyone else experiencing this? Is there a known workaround or is there a known regression with [axios v0.20.0](https://github.com/axios/axios/releases/tag/v0.20.0-0/)? Let me know if I can provide additional information to help demonstrate the issue I am encountering.

**Comment by anttiviljami** [comment]
Can you share how you initialize your OpenAPIClientAxios instance? How are you setting the header token?

**Comment by infomofo** [comment]
I'm initializing my OpenAPIClientAxios method using the `openapi-client-axios-typegen` method outlined in the [README](https://github.com/anttiviljami/openapi-client-axios#generating-type-files-dts) using the `getClient` method: 

```
import OpenAPIClientAxios from "openapi-client-axios";
import { Client } from "client";
const api = new OpenAPIClientAxios({ definition: "/api/openapi.json" });
api.init<Client>();
const client = await api.getClient<Client>();
```

I'm setting the header token as an axios default, as I use the same authorization token for all my api calls.

```axios.defaults.headers.common["Authorization"] = "Bearer " + token```

**Comment by anttiviljami** [comment]
Hi @infomofo ! Could you please make sure you're setting the default headers on the axios client created by `OpenAPIClientAxios` ?

```javascript
const client = await api.getClient<Client>();
axios.defaults.headers["Authorization"] = "Bearer " + token;
```

**Comment by infomofo** [comment]
@anttiviljami This suggested method of setting the bearer token worked with the latest version of axios, thanks!

**Comment by anttiviljami** [comment]
Cheers! 🍺
