### ISSUE TITLE
Dependency json-schema-deref-sync is breaking next.js dev server

### ISSUE THREAD

**Issue by freddydumont** [anttiviljami/openapi-client-axios#38]
I'm getting a `Module not found: Can't resolve 'fs'` when starting the dev server. It appears that `json-schema-deref-sync` is the culprit and it's a dependency of this library.

I'm not really sure what's going on. Any ideas?

![Screen Shot 2020-09-01 at 16 19 36](https://user-images.githubusercontent.com/15388588/91918608-6b219f00-ec91-11ea-9657-c493d12771bc.png)
![Screen Shot 2020-09-01 at 20 25 32](https://user-images.githubusercontent.com/15388588/91918612-6c52cc00-ec91-11ea-87ac-f2335a47cba7.png)

**Comment by ccakes** [comment]
May not be related but I'm getting a number of similar errors trying to use this in a React Native project.

The phone environment doesn't have many native Node modules available like `fs` or `path` which as far as I can tell are only used to read OpenAPI spec files from disk. It'd be good to somehow conditionally load those only if `opts.definition` is a file path.

**Comment by jordiup** [comment]
Would love to use this project on a react native app but i'm getting a similar error 😢
