### ISSUE TITLE
Dependency to the Bath module crashes UglifyJS

### ISSUE THREAD

**Issue by jsslnt** [anttiviljami/openapi-client-axios#4]
Getting an "Unexpected token: punc (,)" error from UglifyJS when running build -- more specifically, to-parameter-pattern.js, line 14.

**Comment by anttiviljami** [comment]
Looks like UglifyJS can't handle anything above es5 whereas bath seems to be targeting es2015. `openapi-client-axios` specifies its target as `es5` so let's come up with a way to get rid of any es2015 or above dependecies.

**Comment by anttiviljami** [comment]
Fixed in v2.1.1
