### ISSUE TITLE
Axios has a new "high" level vuln

### ISSUE THREAD

**Issue by genehack** [anttiviljami/openapi-client-axios#51]
See https://www.npmjs.com/advisories/1594

**Comment by genehack** [comment]
Hi! I realize this isn't a super active project; I was just wondering if there was any chance of getting either the patch the dependbot sent in, or the one I sent it, applied any time soon to get a new release out that doesn't depend on a vulnerable version? 

Thanks for thinking about it.

**Comment by anttiviljami** [comment]
Hi @genehack! Apologies for the delay. I've merged your PR and released `openapi-client-axios@3.8.0`

**Comment by genehack** [comment]
Thanks!
