### ISSUE TITLE
Nuxt integration

### ISSUE THREAD

**Issue by sapyx** [anttiviljami/openapi-client-axios#59]
Thanks for the great job. 
Is integration possible with NUXT and in particular with auth_next? (@nuxtjs/auth-next, @nuxtjs/axios)

thank you

**Comment by espensgr** [comment]
Wondering the same thing!
Or if someone can link to some articles or something on how to implement it.

**Comment by henrycunh** [comment]
i'm currently developing a module for it :]

it'll be a service layer generated from the OAS files, which you can import as a plugin in your `nuxt/auth` module configuration!
