### ISSUE TITLE
I have a slightly different use case, could I use your library to do what I want?

### ISSUE THREAD

**Issue by notyoyoma** [anttiviljami/openapi-client-axios#6]
*My use case:*
I'd like to fetch the swagger.json at webpack compile time, and deliver it as a constant to my app. Then I can create a singleton client from that constant. I already have that working nicely [here](https://github.com/notyoyoma/hakuna-matata) using [swagger-js](https://github.com/swagger-api/swagger-js) as a client.

*What I want to do next:*
I want to write a script to generate a `.d.ts` at webpack compile time (for developer's IntelliSense). Your project is already written in typescript, but swagger-js is not. Do you know how much work it would be to read in a definition, and output a type definition file to document the run-time client?

If you want to add that to your client, I can try to make sure it's compatible.

**Comment by anttiviljami** [comment]
This is something I’ve been trying to work on but turns out is a pretty big task. See #2

**Comment by anttiviljami** [comment]
Hi @notyoyoma I've now implemented a version of this. 

Could you try installing `openapi-client-axios@^3.0.0` and test out the `typegen` script included.

Thanks!

**Comment by notyoyoma** [comment]
Wow, I wasn't expecting you to do work for this, but thanks!

I'm trying to move my code from `swagger-js` to yours, but a few differences are making it difficult.

**Issue 1, (hopefully easy)**
I've been using an example [swagger-v2](https://petstore.swagger.io/v2/swagger.json) json file, but your library uses v3. Do you know if there is a example API that uses OpenApiSpec@v3? I'd be happy to upgrade to get closer to your environment.

**Issue 2, returning a promise, but would prefer synchronous for ease of use.**
With `swagger-js` I was able to do [this](https://github.com/notyoyoma/hakuna-matata/blob/master/client.js#L3-L11), with a usage that looked like this:
```javascript
$hm.apis.pet.addPet()
```

But your library's `init()` function returns a promise, so I think I need to do something like this:
```javascript
const definition = JSON.parse(HAKUNA_MATATA_API_SPEC);
const openApiLib = new OpenAPIClientAxios({definition, validate: false});
const client = openApiLib.init();
// ...
module.exports = client;
```
then the usage would look like this:
```javascript
$hm.then(client => client.addPet())
```
Is there any way to avoid that? I would prefer the usage look like `$hm.addPet()`. I've already resolved the URL, during the webpack compile step, so I don't think I need my client in a promise. (also, forgive me, I still haven't quite wrapped my head around JS promises, and how to use them in certain cases. If there's a way to use `async / await` to get your client, that may be all I need)

**Comment by notyoyoma** [comment]
If it helps you see what I'm doing, [Here](https://github.com/notyoyoma/hakuna-matata/blob/try-openapi-client/client.js) is my library, using your library. (not quite working yet)

and [Here](https://github.com/notyoyoma/hakuna-matata-example) is an example project using my library with yours.

**Comment by anttiviljami** [comment]
You raise a good point about the annoyance of having to initialise the client asynchronously. Even when the document is resolved and perfectly fine.

I've now added a new `.initSync()` method in `openapi-client-axios@3.1.0` for this purpose. Could you have a go and see if this works for your purposes.

Regarding the other issue you raised, feel free to use the test OpenAPI v3 files found in this repository: https://github.com/anttiviljami/openapi-client-axios/tree/master/__tests__/resources

You can also easily convert swagger/openapi v2 files to openapi v3 using this tool: https://github.com/anttiviljami/openapicmd#openapi-swagger2openapi

:)

**Comment by anttiviljami** [comment]
btw I really like what you're doing with your library! :)

**Comment by notyoyoma** [comment]
Thanks! I looked everywhere, and couldn't find anyone who had done what I want, so I'm building it.

I have a long way to go, but I should have an early version done in the next month or so.

Your library might be a fantastic shortcut to get a lot of things I was going to have to build myself, so thanks a ton!

🙏

**Comment by notyoyoma** [comment]
Ah, finally found [this petstoreApi@v3](https://petstore3.swagger.io/) to use as a dummy. After using that URL [here](https://github.com/notyoyoma/hakuna-matata-example/blob/master/hakuna-matata.config.json), I was able to do this:

![$hmworking](https://media.giphy.com/media/PiQxlLSbTUZBOVcFdE/giphy.gif)

Which is exactly the use I wanted! Score! 👍 

Next, the typegen script, so I used your generateTypesForDocument [like this](https://github.com/notyoyoma/hakuna-matata/blob/3fac02e455c0d934b72759d2e6534ff931666d7c/typegen.js), which got me [this globals.d.ts file](https://github.com/notyoyoma/hakuna-matata-example/blob/master/globals.d.ts) Which gets me this intellisense:

![$hmworkingInVSCode](https://media.giphy.com/media/kCzF0k4MBe8yzLhkxX/giphy.gif)

Which isn't perfect, but it's WAY closer than I was expecting to be with only a few hours of work. Next, I'll try to get the intellisense to start auto-completing after the user has only typed `$hm.` but I'm super happy with where we are now!


👍 🍺

**Comment by anttiviljami** [comment]
Yes, it seems like we are solving the same problems from sloghtly different viewpoints. :) I even had the ”mock mode”  feature in an earlier version of `openapi-client-axios`, which I might bring back now that I see you wish to have this feature. :)

**Comment by notyoyoma** [comment]
I will look through your commits, because I want to do some pretty specific things with that. Are you open to pull requests?

**Comment by anttiviljami** [comment]
PRs more than welcome!

**Comment by notyoyoma** [comment]
Hey just an update on this. I am still interested in continuing work on these libraries, but my company lost a few developers and entered a busy time, so working on this stuff will be difficult until later this year.

Thanks for all the help, I look forward to getting back to this!

**Comment by ramast** [comment]
For people who are not sure how to use `initSync `, you basically import your schema first

`import schema from 'schema.json'`

then you provide it to OpenAPIClientAxios instead schema definition url

```javascript
import schema from 'schema.json';

export const apiClient = new OpenAPIClientAxios({
  definition: schema, // instead of '/url/of/schema.json',
  axiosConfigDefaults: {
    xsrfHeaderName: 'X-CSRFTOKEN',
    xsrfCookieName: 'csrftoken',
  },
}).initSync();
```
