### ISSUE TITLE
typegen - how to actually use generated OpenAPI type definitions ? 

### ISSUE THREAD

**Issue by kennymalac** [anttiviljami/openapi-client-axios#65]
There is documentation on calling the actual client methods, but there doesn't seem to be any reference how to deal with the result of the client's response as the actual response type, nor how to import and use these types. The entire purpose of generating these OpenAPI types for me is to actually be able to use these types throughout my code, not just have a typed client with typed methods?
  
Please provide documentation on how to use said type definitions and actually handle the response code. There seems to be no way to import or use any of the response types.
  
Given the (slightly revised for example) code below:
```ts
import { Client as ApiClient } from '@/types/apiTypes'
const api = new OpenAPIClientAxios({ definition: 'http://localhost:8342/openapi.json' })

export async function apiClient() {
  return await api.getClient<ApiClient>()
}

const client = await apiClient()

const result = await client.readReport({ report_type: 'blah', report_id: 'test' })

if (typeof result.data === Components.Schemas.ReportOut) {
    console.log(result.data.details)
    console.log(result.data)
}
```

```
ERROR in utils/api.ts:19:23
TS2304: Cannot find name 'Components'.

ERROR in utils/api.ts:20:64
TS2339: Property 'details' does not exist on type 'ReportOut | HTTPValidationError'.
  Property 'details' does not exist on type 'HTTPValidationError'.

```
How will I be able to type check that report.data is a ReportOut type when it is in a nested namespace I cannot refer to? HTTPValidationError is returned if the response is not successful FYI. I could use "as any" but then I lose any type safety with result.data. I want to be able to use the API's ReportOut type throughout my code.

**Comment by mat813** [comment]
You can't use typeof, as typescript types are only there at compile time and not at runtime. What you can do is this:

```typescript
if ('details' in result.data) { // got Components.Schemas.ReportOut
    console.log(result.data.details)
    console.log(result.data)
}
```

**Comment by kennymalac** [comment]
Understood, that was my mistake, but the solution presented is quite arbitrary... What I would like is to be able use these types and accept them as function arguments:
```
function foo(data: ReportOut) {
  console.log(data.details)
}
```

And also use type guards: https://www.typescriptlang.org/docs/handbook/advanced-types.html

Can we have anyway for the types to be exported?

**Comment by TomFrost** [comment]
In most cases I've encountered, this would be solved by #72. If I omit the error responses from my specs, there's no union type and therefore no need to check for the keys I already know are there.

**Comment by npdev453** [comment]
@kennymalac 
You can use types from responses like this:
```ts
import { Client } from './pet.types'
type DogType = Awaited<ReturnType<Client['getPetById']>>['data']
```
or from requests: 
```ts
type GetPetsQueryParams = Parameters<Client['getPets']>['0']
type GetPetsBodyParams = Parameters<Client['getPets']>['1']
```

Not beautiful solution, but better that nothing. 

Also, I think that schema types from API should not be really used as source of truth for clientside types, or maybe I did not see any use cases.

**Comment by npdev453** [comment]
But anyway, @anttiviljami, 
I really does not understand, why types from `typegen` does not have an `export` keyword, maybe you can explain your vision?

`declare namespace Components {` and `declare namespace Paths {`
could be like `export declare namespace ...` that can expand use cases of this schema. 
(like a server-client types coordination, that could be very useful thing in good hands)
