### ISSUE TITLE
typegen - update dtsgenerator

### ISSUE THREAD

**Issue by sebmasc** [anttiviljami/openapi-client-axios#70]
Please update package dtsgenerator. 
You have 2.5.0 in typegen. Now is 3.10.0 available.

I need changes from https://github.com/horiuchi/dtsgenerator/issues/472 

Thanks a lot!

**Comment by npdev453** [comment]
Will  be fixed by update
https://github.com/anttiviljami/openapi-client-axios/issues/40
https://github.com/anttiviljami/openapi-client-axios/issues/47

**Comment by toaditoad** [comment]
I also run into the `Error: The $ref targets root is not found:`. From what I can see, an update should fix the issue.

**Comment by anttiviljami** [comment]
Done !
