### ISSUE TITLE
Use fetch instead of axios as HTTP client

### ISSUE THREAD

**Issue by jgornick** [anttiviljami/openapi-client-axios#73]
Is it possible to use the `fetch` API as the HTTP client instead of `axios`? In places where the `fetch` API is available (e.g., browser), I'd like to use it instead of including another HTTP client library.

Using [cross-fetch](https://github.com/lquixada/cross-fetch) allows us to use the same `fetch` API across all platforms (e.g., browser, node.js and React Native).

Thanks!

**Comment by anttiviljami** [comment]
Hi @jgornick while I love the idea, that'd be a different library. This lib specifically relies on `axios` features; hence the name. :)

**Comment by anttiviljami** [comment]
Hi @jgornick, this PR #126 might actually now allow this !
