### ISSUE TITLE
Release v4.1 to NPM?

### ISSUE THREAD

**Issue by JoshuaCWebDeveloper** [anttiviljami/openapi-client-axios#79]
Hello! I was looking to use the new `transformOperationMethod` option that is in your official docs, but it seems it has not been released to NPM yet. What are the plans for the 4.1 release?

Thanks!

**Comment by anttiviljami** [comment]
Hi @JoshuaCWebDeveloper ! I've just pushed `4.1.0`.

Hope that helps :)

**Comment by JoshuaCWebDeveloper** [comment]
Awesome! Thanks. 😀
