### ISSUE TITLE
Initialize client using typegen type, excluding openapi definition

### ISSUE THREAD

**Issue by ryan-henness-trimble** [anttiviljami/openapi-client-axios#80]
I was wondering if there is a way that I am able to initialize a client without providing the OpenAPIClientAxios a definition when I've already got a generated type using typegen?

My issue is that the definition will not be public, so I cannot access it at runtime.

```js
const api = new OpenAPIClientAxios({ definition: './oc-openapi.json' }); // Don't want this definition to be passed
api.withServer(OcOpenApiClient.environments[environment]);
api.getClient<Client>().then(client => OcOpenApiClient.instance = client);
```

**Comment by anttiviljami** [comment]
Sorry that still doesn’t seem to make any sense to me. 

What’s your use case exactly?

The definition being passed to generate operation method is the main functionality of this library. I really don’t see a good reason to use this library without passing the definition file

**Comment by ryan-henness-trimble** [comment]
We've got a .NET app that generates the `oc-openapi.d.ts`, and `oc-openapi.json` files. The .NET app also packages those two files along with code to generate a client into an NPM package.

**Comment by npdev453** [comment]
@ryan-henness-trimble 
You can clean all from `oc-openapi.json` except  `operationId` and `path` of methods, other info doesn't use in runtime.

Working with types -- it's an additional feature of this module. Also. d.ts provide only `types` and can't be used in realtime to generate client (without extra magic). 

Another idea, that probably we can generate an static client.js\.ts for schema to not rebuild it every time on client. Especially, it can be actual for large schemas.

**Comment by markoivanovski** [comment]
@anttiviljami I've just come across the same issue so I understand what OP was meaning.

Basically, do we have to specify the URL or Path of our OpenAPI document, given that we've already used `typegen` to generate the necessary types?

In my example, I am using typegen at **build time** from a remote host which generates my API types correctly. Then when I initialize my APIClient, I would like to remove the reliance of connecting to the remote host again to obtain the OpenAPI document.

So, after having used `typegen`, is there a way to initialize `OpenAPIClientAxios` **without** specifying an OpenAPI document inside `definition`, given we already have all the necessary types?

**Comment by busheezy** [comment]
I had the same curiosity which lead me here.
