### ISSUE TITLE
Missing source maps

### ISSUE THREAD

**Issue by arutkowski00** [anttiviljami/openapi-client-axios#82]
Hello,

My app uses webpack and [source-map-loader](https://webpack.js.org/loaders/source-map-loader/). When I'm trying to use this package, I get the following warning during compilation. This is happening because JS files inside openapi-client-axios have `//# sourceMappingURL=<path>`  specified at the bottom, but source maps are not being distributed inside this NPM package.

```WARNING in ./node_modules/openapi-client-axios/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\User\app\node_modules\openapi-client-axios\index.js.map' file: Error: ENOENT: no such file or directory, open 'C:\Users\User\app\node_modules\openapi-client-axios\index.js.map'
 @ ./src/context/ClientContext.tsx 32:0-58 75:23-41
 @ ./src/context/index.ts 4:0-32 4:0-32
 @ ./src/index.tsx 21:0-103 30:25-39 31:32-46 32:34-54 33:36-56
 ```

Could you fix your bundling process to remove this line or actually include source maps?

Thanks!

**Comment by anttiviljami** [comment]
Source maps included in the package from 4.3.4. Thanks for the heads up @arutkowski00! 👍
