### ISSUE TITLE
Error: Cannot find module './typegen/typegen' 

### ISSUE THREAD

**Issue by meabed** [anttiviljami/openapi-client-axios#89]
Last release has an this issue 
in `/openapi-client-axios/index.js`
![image](https://user-images.githubusercontent.com/45731/142735187-79de4efe-5f12-4f44-b791-cc433efe2289.png)

**Comment by SeanLMcCullough** [comment]
+1, downgrading to v4.2.0 solves the problem.

**Comment by anttiviljami** [comment]
Ahh. Will revert this. 👍
