### ISSUE TITLE
How can I use the axios interceptors with this?

### ISSUE THREAD

**Issue by ONiAd** [anttiviljami/openapi-client-axios#9]
I need configure interceptors in order to check token for auth. How can I add this, and how can I set a default config fore every request?

Thx

**Comment by TheMaaarc** [comment]
@ONiAd You can just add the interceptors to the returned client and they will persist.

```js
const client = await api.getClient()
client.interceptors.request.use(/* interceptor */)
client.interceptors.response.use(/* interceptor */)

const client2 = await api.getClient() // Still has the interceptors
```

Obviously this only works if you can guarantee that the code above will be executed before every other `getClient()` call.

**Comment by ONiAd** [comment]
@TheMaaarc Thank you for the help! I will try it! nowadays I've solved just with Axios and creating repositories but I'll need it.
